title: Let's Talk Data
email: curtis.cjames91@gmail.com
author:
  picture: https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/10885564_10205512316312359_2797026943429185315_n.jpg?oh=4a6fc344099449aa1ddf0e5dc99f84d8&oe=595001ED #URL FORMAT
  name: Curtis James
  location: New York City
  description: "Former data analyst, turned research assistant, turned data engineer. I'm currently a consultant at the World Bank Group"  
description: casper theme jekyll site
baseurl: "/"
url: https://curtcjay.github.io/
twitter_username: curtisjame_s
github_username:  curtcjay
github_url: https://github.com/curtcjay

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
